data:
  class_path: timeprophet.data_modules.MultivarDataModule
  init_args:
    dataset_path: dataset/weather.csv.gz
    batch_size: 128
    input_len: 720
    output_len: 336
    x_features: null
    y_features: null
    all_features_num: 21
    preprocessor: sklearn.preprocessing.StandardScaler
    pin_memory: true
    num_workers: 4
    persistent_workers: true
