blank_issues_enabled: false
contact_links:
  - name: Q & A
    url: https://github.com/wintertee/DiPE-Linear/discussions/new?category=q-a
    about: Questions if you need help.
  - name: Ideas
    url: https://github.com/wintertee/DiPE-Linear/discussions/new?category=ideas
    about: For feature requests.
  - name: Bugs report
    url: https://github.com/wintertee/DiPE-Linear/discussions/new?category=general
    about: For suspected bugs or weird things.
