data:
  class_path: timeprophet.data_modules.MultivarDataModule
  init_args:
    dataset_path: dataset/traffic.csv.gz
    batch_size: 64
    input_len: 720
    output_len: 96
    x_features: null
    y_features: null
    all_features_num: 862
    preprocessor: sklearn.preprocessing.StandardScaler
    pin_memory: true
    num_workers: 4
    persistent_workers: true
